### ISSUE TITLE
Issues implementing module

### ISSUE THREAD

**Issue by Esity** [joshbeard/puppet-graylog_collector#3]
I cannot get the graylog-collector class to load. Not sure if this is a bug but I am thinking it is a setup problem. Any way you can help me out getting this implemented?

**Comment by Esity** [comment]
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type graylog_collector::output

**Comment by joshbeard** [comment]
Looks like the module isn't in your module path or isn't readable.

How did you install the module?

**Comment by Esity** [comment]
I think I did a git clone into modules.

**Comment by Esity** [comment]
when i type puppet module list i see this in the list

── puppet-graylog_collector (???)

**Comment by joshbeard** [comment]
Make sure the directory name of the module is `graylog_collector` and NOT `puppet-graylog_collector`.

**Comment by Esity** [comment]
So I did change the class to graylog_collector and it actually loads the class however I am still seeing an error.

Error: Failed to apply catalog: Could not find dependent Exec[concat_/collector.conf] for File[/var/lib/puppet/concat/_collector.conf/fragments/401_output_graylog-server] at /etc/puppet/modules/concat/manifests/fragment.pp:132

class profile::base::graylog {
  graylog_collector::output { 'graylog-server':
    type => 'gelf',
    host => '1.1.1.1',
    port => '11111',
  }
}

**Comment by joshbeard** [comment]
Have you declared the `graylog_collector` class?  This message looks like it's complaining that the base config isn't present.  Declaring `graylog_collector` handles that.  So in your example, you should do something like

``` puppet
  class { '::graylog_collector':
    server_url => '127.0.0.1:12900',
  }
```

To setup the "base" stuff, specifying your Graylog server's address there.  Note that your Graylog server will need to be configured with an input for this.

**Comment by Esity** [comment]
So that seemed to help however now I am seeing this

Notice: /Stage[main]/Graylog_collector::Install::Archive/File[/usr/share/graylog-collector]: Not removing directory; use 'force' to override
Notice: /Stage[main]/Graylog_collector::Install::Archive/File[/usr/share/graylog-collector]: Not removing directory; use 'force' to override
Error: Could not remove existing file
Error: /Stage[main]/Graylog_collector::Install::Archive/File[/usr/share/graylog-collector]/ensure: change from directory to link failed: Could not remove existing file
Notice: /Stage[main]/Graylog_collector::Config/File[/etc/default/graylog-collector]: Dependency File[/usr/share/graylog-collector] has failures: true
Warning: /Stage[main]/Graylog_collector::Config/File[/etc/default/graylog-collector]: Skipping because of failed dependencies
Notice: /Stage[main]/Graylog_collector::Config/Concat[/etc/graylog-collector/collector.conf]/File[/var/lib/puppet/concat/_etc_graylog-collector_collector.conf]: Dependency File[/usr/share/graylog-collector] has failures: true
Warning: /Stage[main]/Graylog_collector::Config/Concat[/etc/graylog-collector/collector.conf]/File[/var/lib/puppet/concat/_etc_graylog-collector_collector.conf]: Skipping because of failed dependencies

**Comment by joshbeard** [comment]
Hmm, this kind of looks like `/usr/share/graylog-collector` already exists.  Does it?  The module manages a symlink, which it tries to create at `/usr/share/graylog-collector` and links it to the version (e.g. `/usr/share/graylog-collector-0.4.0`

If you already have a `/usr/share/graylog-collector` and it's NOT a symlink, try renaming it.

**Comment by Esity** [comment]
Wow everything works great! thank you for the help!! I really appreciate it

**Comment by Esity** [comment]
Ok I just realized something else. the puppet module will create the config in /etc/graylog-collector/collector.conf but with new installations, the config is actually stored in /etc/graylog/collector/collector.conf

Any ideas?

**Comment by Esity** [comment]
Ok sorry. RTFM I know.

config_dir => '/etc/graylog/collector', Thanks for everything
